services:
  # PostgreSQL Database
  db:
    image: postgres:14.18
    environment:
      - POSTGRES_DB=${DB_NAME:-jenkinsdb}
      - POSTGRES_USER=${DB_USER:-jenkins_admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:-jenkinsdb}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-jenkins_admin}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:8082}
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 